
# default versions
ARG AZURE_CLI_VERSION=2.0.80
# azure cli image
FROM alpine:latest as azure-cli
ARG AZURE_CLI_VERSION
RUN apk add --no-cache curl tar openssl bash jq python3 && \
    if [ ! -e /usr/bin/python ]; then ln -sf python3 /usr/bin/python ; fi
RUN apk add --virtual=build gcc libffi-dev musl-dev openssl-dev make python3-dev
RUN pip3 install --upgrade pip && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi
RUN pip3 install --upgrade azure-cli==${AZURE_CLI_VERSION}
RUN apk del --purge build